// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "hexagony/auth/domain"

	mock "github.com/stretchr/testify/mock"
)

// AuthUseCase is an autogenerated mock type for the AuthUseCase type
type AuthUseCase struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: ctx, email, password
func (_m *AuthUseCase) Authenticate(ctx context.Context, email string, password string) (*domain.AuthToken, error) {
	ret := _m.Called(ctx, email, password)

	var r0 *domain.AuthToken
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.AuthToken); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthToken)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewAuthUseCaseT interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthUseCase creates a new instance of AuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthUseCase(t NewAuthUseCaseT) *AuthUseCase {
	mock := &AuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
