version: "3.9"

services:
  # mariadb:
  #   image: mariadb:10.8.3
  #   container_name: hexagony-database
  #   hostname: hexagony-database
  #   restart: unless-stopped
  #   volumes:
  #     - ./db/mariadb:/docker-entrypoint-initdb.d
  #     - ./db/mariadb/.data:/var/lib/mysql
  #   ports:
  #     - ${DB_PORT}:${DB_PORT}
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=${DB_PASS}
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "-u$DB_USER", "-p$DB_PASS", "ping", "-h", "localhost"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   env_file: .env

  postgres:
    image: postgres:14.4-alpine
    container_name: hexagony-database-pg
    hostname: hexagony-database-pg
    restart: unless-stopped
    volumes:
      - ./db/postgres:/docker-entrypoint-initdb.d/
      - ./db/postgres/.data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata # named volume (windows workaround to persist data)
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
     test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
     interval: 10s
     timeout: 5s
     retries: 5
    env_file: .env

  api:
    build:
      context: .
    container_name: hexagony-api
    hostname: hexagony-api
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    depends_on:
      postgres: # change to mariadb if you want
        condition: service_healthy
    env_file: .env
