version: "3.9"

services:
  mysql:
    image: mysql:5.7.38
    container_name: hexagony-database
    hostname: hexagony-database
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/.data:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    healthcheck:
      test: ["CMD", "mysqladmin", "-u$DB_USER", "-p$DB_PASS", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 30s
      retries: 3
    env_file: .env

  api:
    build:
      context: .
    container_name: hexagony-api
    hostname: hexagony-api
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      mysql:
        condition: service_healthy
    env_file: .env
